### PR TITLE
[WIP] [Feature] Command Tree & Parser

### PR DESCRIPTION
**Pull request by MSDNicrosoft**

### CODE REVIEW

**Review by shenjackyuanjie — COMMENTED** [review]
aaa

**Review by shenjackyuanjie — COMMENTED** [review]
ok

**Comment by MSDNicrosoft** [comment]
https://github.com/shenjackyuanjie/Difficult-Rocket/pull/51/files#diff-09704484fecba8af6ecc28a399a53d6e232bfde147d029ab6d6801d1bc4df00eR76-R80

**Comment by MSDNicrosoft** [comment]
https://github.com/shenjackyuanjie/lib-not-dr/blob/b045271a8082c657eaceeea4a3c96edba602e2e4/lib_not_dr/command/data.py#L6-L8

**Comment by MSDNicrosoft** [comment]
Deprecated.

**Comment by shenjackyuanjie** [comment]
reeeeeeeeeeeeee

**Pull request closed without merging**
